"""create feedback table

Revision ID: 20ea021ffe7d
Revises: 878fca00b7b3
Create Date: 2026-07-13 19:56:42.378442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ea021ffe7d'
down_revision: Union[str, Sequence[str], None] = '878fca00b7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('caffeine_consumption', sa.Integer(), nullable=False),
    sa.Column('alcohol_consumption', sa.Integer(), nullable=False),
    sa.Column('smoking_status', sa.Integer(), nullable=False),
    sa.Column('exercise_frequency', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
