"""feat(tracker): add updated_at column

Revision ID: 26688d79bcf1
Revises: 5ec6580e0f01
Create Date: 2026-07-29 10:22:23.844984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26688d79bcf1'
down_revision: Union[str, Sequence[str], None] = '5ec6580e0f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackers', 'updated_at')
    # ### end Alembic commands ###
