"""feat!(trackers): added not null sleepDuration & sleepEfficiency column heheheheheh

Revision ID: ad9ca2b7d284
Revises: 26688d79bcf1
Create Date: 2026-07-29 15:25:20.583106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9ca2b7d284'
down_revision: Union[str, Sequence[str], None] = '26688d79bcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trackers', sa.Column('sleepDuration', sa.Float(), nullable=False))
    op.add_column('trackers', sa.Column('sleepEfficiency', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trackers', 'sleepEfficiency')
    op.drop_column('trackers', 'sleepDuration')
    # ### end Alembic commands ###
