"""add tracker table

Revision ID: ef044e687bb4
Revises: 20ea021ffe7d
Create Date: 2026-07-26 12:01:55.066839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef044e687bb4'
down_revision: Union[str, Sequence[str], None] = '20ea021ffe7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wakeup', sa.String(), nullable=False),
    sa.Column('bedtime', sa.String(), nullable=False),
    sa.Column('awakenings', sa.Integer(), nullable=False),
    sa.Column('timeInBed', sa.Integer(), nullable=False),
    sa.Column('isGoodSleep', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trackers_id'), 'trackers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trackers_id'), table_name='trackers')
    op.drop_table('trackers')
    # ### end Alembic commands ###
