"""create feedback table

Revision ID: efd7e6409e1d
Revises: 6cfe6c732037
Create Date: 2026-07-13 13:43:54.881378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd7e6409e1d'
down_revision: Union[str, Sequence[str], None] = '6cfe6c732037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sleep_duration', sa.Integer(), nullable=False),
    sa.Column('awakenings', sa.Integer(), nullable=False),
    sa.Column('sleep_efficiency', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
